#!/usr/bin/env bash
# Day 0 — kubeadm on EC2. Independent of Kind.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ENV_DIR="${REPO_ROOT}/infra/terraform/environments/ec2"
AUTO_APPROVE=""
CLUSTER_SPEC="default"
K8S_TF_VAR_ARGS=()

usage() {
  cat <<EOF
Usage: ./scripts/infra/aws/up.sh [cluster] [-y]

Apply AWS EC2 lab (terraform environments/ec2) for exactly one cluster config.

  cluster     id or path (default: default)
              config/aws/clusters/<id>.yaml
  -y, --yes   terraform apply -auto-approve

Teardown: $(dirname "$0")/down.sh [cluster]
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    -y | --yes)
      AUTO_APPROVE="-auto-approve"
      ;;
    -c | --cluster)
      CLUSTER_SPEC="${2:?cluster config required}"
      shift
      ;;
    *)
      CLUSTER_SPEC="$1"
      ;;
  esac
  shift
done

if [[ ! -d "$ENV_DIR" ]]; then
  echo "Terraform environment not found: $ENV_DIR" >&2
  exit 1
fi

echo "==> AWS: ${ENV_DIR}"
"$REPO_ROOT/scripts/lib/require-tools.sh" terraform aws
# shellcheck source=scripts/lib/aws-env.sh
source "$REPO_ROOT/scripts/lib/aws-env.sh"
k8s_plat_resolve_cluster_config aws "${CLUSTER_SPEC}"
k8s_plat_apply_cluster_outputs
k8s_plat_require_aws_credentials
k8s_plat_load_provider_vars
echo "==> AWS identity (project credentials: ${AWS_SHARED_CREDENTIALS_FILE})"
aws sts get-caller-identity --no-cli-pager

cd "$ENV_DIR"
k8s_plat_terraform_init "$ENV_DIR"
# shellcheck disable=SC2086
terraform apply -input=false $AUTO_APPROVE "${K8S_TF_VAR_ARGS[@]}"

write_cluster_env() {
  local envf="${K8S_PLAT_CLUSTER_ENV}"
  local cp_host ssh_key workers k8s_version pod_cidr
  mkdir -p "${K8S_PLAT_CLUSTER_DIR}"
  cp_host="$(terraform output -raw control_plane_public_ip)"
  ssh_key="$(terraform output -raw ssh_private_key_path)"
  workers="$(terraform output -raw worker_public_ips)"
  k8s_version="$(k8s_plat_aws_infra_get kubernetes_version 2>/dev/null || echo "1.32")"
  pod_cidr="$(k8s_plat_aws_infra_get pod_cidr 2>/dev/null || echo "192.168.0.0/16")"
  cat >"${envf}" <<EOF
# Generated by scripts/infra/aws/up.sh — do not commit.
CLUSTER_NAME=${K8S_PLAT_CLUSTER_NAME}
SSH_USER=ubuntu
SSH_KEY=${ssh_key}
CONTROL_PLANE_HOST=${cp_host}
CONTROL_PLANE_ENDPOINT=${cp_host}
WORKER_HOSTS=${workers}
K8S_VERSION=${k8s_version}
POD_CIDR=${pod_cidr}
KUBECONFIG_FILE=${K8S_PLAT_CLUSTER_KUBECONFIG}
SSH_CONTROL_PLANE=ssh -i ${ssh_key} ubuntu@${cp_host}
EOF
  chmod 600 "${envf}"
  echo "==> Wrote cluster outputs ${envf}"
}

write_cluster_env

echo ""
echo "Terraform aws applied (VMs only; Kubernetes is separate)."
terraform output
echo ""
echo "Next (kubeadm):"
echo "  ${REPO_ROOT}/scripts/infra/kubeadm/up.sh ${K8S_PLAT_CLUSTER_NAME}"
echo "Then Day 1: source scripts/lib/kubeconfig-setup.sh clusters/${K8S_PLAT_CLUSTER_NAME}/kubeconfig"
echo "  ${REPO_ROOT}/bootstrap/bootstrap.sh dev"
