#!/usr/bin/env bash
# Day 0 — kubeadm on OpenStack VMs. Independent of Kind and AWS.

if [ -z "${BASH_VERSION:-}" ] || [ -n "${POSIXLY_CORRECT:-}" ]; then
  exec /usr/bin/env bash "$0" "$@"
fi

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ENV_DIR="${REPO_ROOT}/infra/terraform/environments/openstack"
AUTO_APPROVE=""
CLUSTER_SPEC=""
K8S_TF_VAR_ARGS=()

usage() {
  cat <<EOF
Usage: ./scripts/infra/openstack/up.sh [cluster] [-y]

Apply OpenStack lab (terraform environments/openstack) for exactly one cluster config.

  cluster     id or path (required). clusters/openstack/<id>/config.yaml
  -y, --yes   terraform apply -auto-approve

Attaches VMs to an existing Neutron network (does not create or delete that network).

Teardown: ./scripts/infra/down.sh openstack [cluster]
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    -y | --yes)
      AUTO_APPROVE="-auto-approve"
      ;;
    -c | --cluster)
      CLUSTER_SPEC="${2:?cluster config required}"
      shift
      ;;
    *)
      CLUSTER_SPEC="$1"
      ;;
  esac
  shift
done

if [[ ! -d "$ENV_DIR" ]]; then
  echo "Terraform environment not found: $ENV_DIR" >&2
  exit 1
fi

echo "==> OpenStack: ${ENV_DIR}"
"$REPO_ROOT/scripts/lib/require-tools.sh" terraform
# shellcheck source=scripts/lib/os-env.sh
source "$REPO_ROOT/scripts/lib/os-env.sh"
k8s_plat_resolve_cluster_config openstack "${CLUSTER_SPEC}"
k8s_plat_apply_cluster_outputs
k8s_plat_require_os_credentials
k8s_plat_load_os_provider_vars

if command -v openstack >/dev/null 2>&1; then
  echo "==> OpenStack identity (OS_CLOUD=${OS_CLOUD}; token secret not printed)"
  openstack token issue -f value -c project_id -c user_id -c expires || true
else
  echo "==> openstack CLI not on PATH (optional). Terraform uses clouds.yaml."
fi

cd "$ENV_DIR"
k8s_plat_terraform_init "$ENV_DIR"
# shellcheck disable=SC2086
terraform apply -input=false $AUTO_APPROVE "${K8S_TF_VAR_ARGS[@]}"

write_cluster_env() {
  local envf="${K8S_PLAT_CLUSTER_ENV}"
  local cp_host ssh_key workers k8s_version pod_cidr ssh_user octavia_env cloud_provider cni_env
  mkdir -p "${K8S_PLAT_CLUSTER_DIR}"
  cp_host="$(terraform output -raw control_plane_public_ip)"
  ssh_key="$(terraform output -raw ssh_private_key_path)"
  workers="$(terraform output -raw worker_public_ips)"
  ssh_user="$(terraform output -raw ssh_user)"
  octavia_env="$(terraform output -json octavia_lb_vips 2>/dev/null | python3 -c '
import json, sys
raw = sys.stdin.read().strip() or "{}"
vips = json.loads(raw)
if not isinstance(vips, dict):
    vips = {}
print("INGRESS_LB_VIP=" + str(vips.get("ingress", "")))
print("OCTAVIA_LB_NAMES=" + " ".join(vips.keys()))
for name, ip in vips.items():
    key = name.upper().replace("-", "_")
    print(f"OCTAVIA_LB_VIP_{key}={ip}")
')"
  k8s_version="$(k8s_plat_yaml_require "${K8S_PLAT_CLUSTER_CONFIG}" kubernetes_version)" || return 1
  pod_cidr="$(k8s_plat_yaml_require "${K8S_PLAT_CLUSTER_CONFIG}" pod_cidr)" || return 1
  # Optional: "external" makes kubeadm/up.sh set --cloud-provider=external.
  cloud_provider="$(k8s_plat_yaml_get "${K8S_PLAT_CLUSTER_CONFIG}" cloud_provider || true)"
  cni_env="$(k8s_plat_cni_env_lines)"
  cat >"${envf}" <<EOF
# Generated by scripts/infra/openstack/up.sh — do not commit.
CLUSTER_NAME=${K8S_PLAT_CLUSTER_NAME}
SSH_USER=${ssh_user}
SSH_KEY=${ssh_key}
CONTROL_PLANE_HOST=${cp_host}
CONTROL_PLANE_ENDPOINT=${cp_host}
WORKER_HOSTS=${workers}
K8S_VERSION=${k8s_version}
POD_CIDR=${pod_cidr}
${cni_env}
CLOUD_PROVIDER=${cloud_provider}
KUBECONFIG_FILE=${K8S_PLAT_CLUSTER_KUBECONFIG}
SSH_CONTROL_PLANE=ssh -i ${ssh_key} ${ssh_user}@${cp_host}
${octavia_env}
EOF
  chmod 600 "${envf}"
  echo "==> Wrote cluster outputs ${envf}"
}

write_cluster_env

echo ""
echo "Terraform openstack applied (VMs only; Kubernetes is separate)."
echo "Existing Neutron network was looked up, not created."
terraform output
echo ""
echo "Next (kubeadm):"
echo "  ${REPO_ROOT}/scripts/infra/kubeadm/up.sh ${K8S_PLAT_CLUSTER_PLATFORM} ${K8S_PLAT_CLUSTER_CONFIG_ID}"
