apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-latest
  namespace: chainsaw-disallow-latest-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-latest
  template:
    metadata:
      labels:
        app: bad-latest
    spec:
      containers:
        - name: nginx
          image: nginx:latest
